package:
  name: "fastfetch"
  version: "2.39.0"
  type: "binary"
  architecture: "x86_64"
  description: "Fast system information tool"
  maintainer: "AnmiTaliDev <anmitali198@gmail.com>"
  license: "MIT"
  homepage: "https://github.com/fastfetch-cli/fastfetch"
  tags: ["system", "info", "cli", "neofetch", "nuros"]
  dependencies: []
  conflicts: []
  provides: []
  replaces: []
  conf: []

source:
  url: "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.39.0.tar.gz"

build:
  dependencies: ["build-essential", "cmake"]
  script: |
    mkdir build
    cd build
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_SYSTEM_YYJSON=OFF
    make -j$(nproc)
    cd ..

install:
  script: "cd build && make DESTDIR=\"$DESTDIR\" install"
